
import React from 'react';
import { 
  Play, 
  Wand2, 
  Image as ImageIcon, 
  Type, 
  Languages, 
  Scissors, 
  User, 
  ArrowRight,
  ArrowLeft,
  Check,
  Video,
  VideoOff,
  Mic,
  LayoutTemplate,
  Loader2,
  ChevronRight,
  Monitor,
  Smartphone,
  Square,
  Layout,
  Mail,
  Lock,
  CreditCard,
  Bell,
  Settings,
  LogOut,
  FileText,
  Shield,
  Eye,
  EyeOff,
  Github,
  Cloud,
  RefreshCw,
  AlertCircle,
  Download,
  X,
  Maximize2,
  Plus,
  Trash2,
  Edit3,
  Save,
  Globe,
  Film,
  RotateCcw,
  Search,
  Clock,
  ChevronDown,
  Key
} from 'lucide-react';

export const Icons = {
  Play, Wand2, ImageIcon, Type, Languages, Scissors, User, ArrowRight, ArrowLeft, Check, Video, VideoOff, Mic, LayoutTemplate, Loader2, ChevronRight,
  Monitor, Smartphone, Square, Layout,
  Mail, Lock, CreditCard, Bell, Settings, LogOut, FileText, Shield, Eye, EyeOff, Github, Cloud,
  RefreshCw, AlertCircle, Download, X, Maximize2,
  Plus, Trash2, Edit3, Save, Globe, Film, RotateCcw, Search, Clock,
  ChevronDown, Key
};
